// publish() — ties plan + gate + generated static-host files together. The output `files` map
// is a virtual filesystem a shell adapter / CI writes to disk, same posture as @3jse/project.

import { planBuild, type PlanInput } from "./plan.js";
import { checkPublishGate, type GateInput } from "./gate.js";
import type { BuildOptions, PublishResult, ThirdPartyNotice } from "./types.js";

export function generateThirdPartyNotices(notices: ThirdPartyNotice[]): string {
  if (notices.length === 0) return "# Third-Party Notices\n\nThis build ships no third-party code requiring attribution.\n";
  const body = [...notices]
    .sort((a, b) => a.packageName.localeCompare(b.packageName))
    .map(
      (n) =>
        `## ${n.packageName}\n\n- Source: ${n.source}\n- License: ${n.license}\n- Author: ${n.author}\n`,
    )
    .join("\n");
  return `# Third-Party Notices\n\nThis build includes the following third-party components:\n\n${body}`;
}

/** The generated game bootstrap (docs/BUILD_DEPLOYMENT.md step 4). Boots a project headless of
 *  the editor: loads the start scene, builds the World, runs the fixed/variable tick in a rAF
 *  loop against a WebGPURenderer. Emitted as source; the bundler compiles it. */
function bootstrapSource(startScene: string | null): string {
  return `import * as THREE from "three/webgpu";
import { World } from "@3jse/runtime";
import { loadProject } from "@3jse/project";

// Generated by @3jse/packaging. Do not edit — re-publish instead.
const START_SCENE = ${JSON.stringify(startScene)};

async function boot() {
  const files = await (await fetch("./project.json")).json();
  const world = new World();
  const { levels } = loadProject(world, files);
  const level = START_SCENE ? world.getLevel(START_SCENE) : levels[0];
  if (!level) throw new Error("start scene not found");

  const canvas = document.getElementById("game");
  const renderer = new THREE.WebGPURenderer({ canvas, antialias: true });
  await renderer.init();
  const camera = new THREE.PerspectiveCamera(60, 1, 0.1, 1000);
  camera.position.set(0, 4, 10);
  const resize = () => {
    renderer.setSize(canvas.clientWidth, canvas.clientHeight, false);
    camera.aspect = canvas.clientWidth / canvas.clientHeight;
    camera.updateProjectionMatrix();
  };
  new ResizeObserver(resize).observe(canvas);
  resize();

  world.play();
  let last = performance.now();
  function frame() {
    requestAnimationFrame(frame);
    const now = performance.now();
    const dt = Math.min((now - last) / 1000, 0.1);
    last = now;
    world.step(dt);
    renderer.render(level.scene, camera);
  }
  frame();
}

boot();
`;
}

function indexHtml(projectName: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <title>${escapeHtml(projectName)}</title>
  <style>html,body{margin:0;height:100%;background:#000;overflow:hidden}#game{width:100vw;height:100vh;display:block}</style>
</head>
<body>
  <canvas id="game"></canvas>
  <script type="module" src="./bootstrap.js"></script>
</body>
</html>
`;
}

function pwaManifest(projectName: string): string {
  return JSON.stringify(
    {
      name: projectName,
      short_name: projectName.slice(0, 12),
      start_url: "./",
      display: "fullscreen",
      background_color: "#000000",
      theme_color: "#000000",
    },
    null,
    2,
  );
}

function serviceWorker(buildId: string): string {
  return `const CACHE = "3jse-${buildId}";
self.addEventListener("install", (e) => e.waitUntil(caches.open(CACHE)));
self.addEventListener("activate", (e) =>
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k))))),
);
self.addEventListener("fetch", (e) =>
  e.respondWith(caches.open(CACHE).then((c) => c.match(e.request).then((r) => r || fetch(e.request).then((res) => { c.put(e.request, res.clone()); return res; })))),
);
`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);
}

export interface PublishInput extends PlanInput {
  gate?: Omit<GateInput, "manifest">;
}

/** Run the full Publish pipeline: plan -> gate -> generate host files. `ok` is false (and
 *  `manifest` still returned for inspection) if the gate has any error. */
export function publish(input: PublishInput, opts: BuildOptions): PublishResult {
  const manifest = planBuild(input, opts);
  const issues = checkPublishGate({ manifest, ...(input.gate ?? {}) });
  const ok = !issues.some((i) => i.level === "error");

  const files: Record<string, string> = {
    "manifest.json": JSON.stringify(manifest, null, 2),
    "THIRD_PARTY_NOTICES.md": generateThirdPartyNotices(manifest.notices),
    "index.html": indexHtml(input.projectName),
    "bootstrap.js": bootstrapSource(input.startScene),
  };
  if (opts.target === "pwa") {
    files["manifest.webmanifest"] = pwaManifest(input.projectName);
    files["sw.js"] = serviceWorker(manifest.buildId);
  }

  return { ok, manifest: ok ? manifest : manifest, issues, files: ok ? files : {} };
}
