// `3jse publish` — runs @3jse/packaging's publish() and writes the output. Reuse-first: the
// actual JS bundling defers to esbuild (loaded dynamically; if absent, a build.mjs is emitted
// for the user to run) rather than reimplementing a bundler.

import { publish, type BuildTarget, type QualityTier, type PublishInput, type BuildOptions } from "@3jse/packaging";

export interface PublishCliOptions {
  projectName: string;
  engine: string;
  dependencies: Record<string, string>;
  usedPackages: string[];
  scenes: string[];
  startScene: string | null;
  /** path -> content of every project file, to hash + ship as data */
  projectFiles: Record<string, string>;
  target: BuildTarget;
  tier: QualityTier;
  keepLodTiers?: number[];
}

export interface PublishCliResult {
  ok: boolean;
  buildId: string | null;
  /** output path -> file content, ready to write to `outDir` */
  files: Record<string, string>;
  issues: { level: "error" | "warn"; message: string }[];
  /** true when esbuild bundled bootstrap.js; false when a build.mjs was emitted instead */
  bundled: boolean;
}

/** Pure core: build the publish output. `bundleBootstrap` is injected so a test can stub it and
 *  the bin can wire the real esbuild. */
export async function runPublish(
  opts: PublishCliOptions,
  bundleBootstrap?: (source: string) => Promise<string>,
): Promise<PublishCliResult> {
  const input: PublishInput = {
    projectName: opts.projectName,
    engine: opts.engine,
    dependencies: opts.dependencies,
    usedPackages: opts.usedPackages,
    scenes: opts.scenes,
    startScene: opts.startScene,
    assets: Object.entries(opts.projectFiles).map(([path, content]) => ({ path, content, kind: "data" as const })),
    graphs: [],
    notices: [],
  };
  const buildOpts: BuildOptions = { target: opts.target, tier: opts.tier, keepLodTiers: opts.keepLodTiers ?? [0], production: true };
  const result = publish(input, buildOpts);

  if (!result.ok || !result.manifest) {
    return { ok: false, buildId: null, files: {}, issues: result.issues, bundled: false };
  }

  const files: Record<string, string> = { ...result.files, "project.json": JSON.stringify(opts.projectFiles) };
  let bundled = false;
  const bootstrap = files["bootstrap.js"];
  if (bootstrap && bundleBootstrap) {
    try {
      files["bootstrap.js"] = await bundleBootstrap(bootstrap);
      bundled = true;
    } catch (e) {
      result.issues.push({ level: "warn", code: "bundle-skipped", message: `esbuild bundling failed: ${(e as Error).message}` });
    }
  }
  if (!bundled) {
    files["build.mjs"] = buildScript(opts.target);
  }

  return { ok: true, buildId: result.manifest.buildId, files, issues: result.issues, bundled };
}

function buildScript(target: BuildTarget): string {
  return `// Generated by @3jse/cli. Run \`node build.mjs\` (needs esbuild installed) to bundle bootstrap.js.
import { build } from "esbuild";
await build({
  entryPoints: ["bootstrap.js"],
  bundle: true,
  format: "esm",
  minify: true,
  target: "es2022",
  outfile: "bootstrap.bundle.js",
  loader: { ".wasm": "file" },
});
console.log("bundled -> bootstrap.bundle.js for target ${target}");
`;
}
